server:
  port: 8080
  servlet:
    context-path: /
    
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource:
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: blog
    password: bitc5600
    
file: 
  path: 'C:/Users/it/Documents/workspace-spring-tool-suite-4-4.4.1.RELEASE/blog/src/main/webapp/resources/images/user/'